### ISSUE TITLE
REXML::ParseException: Malformed comment

### ISSUE THREAD

**Issue by anam-mansoor7** [x12ruby/x12#4]
I get the exception below when I try to create a  850 PO parser.
parser = X12::Parser.new('system/misc/850.xml')
I am using ruby 1.9.3 and rails 3.2.11. I did not get this exception in ruby 1.8.7.
Stack Trace
REXML::ParseException: #<REXML::ParseException: Malformed comment
Line: 33
Position: 2642
Last 80 unconsumed characters:

> /home/anam/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:346:in `pull_event'
> /home/anam/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:183:in`pull'
> /home/anam/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/rexml/parsers/treeparser.rb:22:in `parse'
> /home/anam/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/rexml/document.rb:231:in`build'
> /home/anam/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/rexml/document.rb:43:in `initialize'
> /home/anam/.rvm/gems/ruby-1.9.3-p194@up_mp/bundler/gems/x12-b8f38e183a6f/lib/x12/xmldefinitions.rb:37:in`new'

**Comment by swalberg** [comment]
Hi,

Have a look at dd3f734674c, there was a similar error in this project when I moved it to 1.9.3. Ended up being a problem with the xml file.

Failing that, can you throw your 850.xml in a gist?

**Comment by anam-mansoor7** [comment]
The contents of 850.xml file are below
http://pastebin.com/cfQxZ2jp

**Comment by swalberg** [comment]
Thanks for providing that. I was able to parse it correctly.

Are you using the code from this repo? The gem version is behind -- I don't actually control it so I can't update it to use the improvements we've made here.

**Comment by anam-mansoor7** [comment]
I am using the gem version

**Comment by swalberg** [comment]
Aha. You'll want to point to this repo for the latest code. I've asked the original author to let me push updates to the gem.

**Comment by swalberg** [comment]
I'm going to close this ticket as there's nothing to be done and a resolution has been offered.

I've asked the author again to let me push to the original gem. After the last message to him we agreed that I'd move the repo to its own organization which has been done.

**Comment by anam-mansoor7** [comment]
There were some special character in the xml that was causing this exception.
